apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: kyosk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: asia-east1-docker.pkg.dev/rs-0123/kyoskdemo/test-app1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
