apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: asia-east1-docker.pkg.dev/rs-0123/kyoskdemo/test-app1:1f50d1e
          ports:
            - containerPort: 80

